# Generated by Django 4.1.6 on 2023-03-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="username",),
    ]
